language: node_js
install:
  - "npm install npm@~1.4.23 -g"
  - "npm install grunt-cli -g"
  - "npm install codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt test"
node_js:
  - "0.12"
  - "0.11"
  - "0.10"